run:
	- echo Starting development server
	FLASK_APP=server.py flask run

install:
	- echo install PIP deps
	pip3 install -r requirements.txt
	py init_db.py

pytest:
	- echo testing with PyTest
	py -m pytest